godwokenrises/godwoken-kicker

.gitmodules, web3-sql/create_tables.sql
https://github.com/nervosnetwork/godwoken-web3/pull/3
This PR fixes the returned value of eth_sendRawTransaction
=> Upgrade godwoken & godwoken-web3 to v0.2.1 tag

Makefile, docker/docker-compose.yml, docker/layer1/Dockerfile, docker/layer2/Dockerfile.example, docker/web3/Dockerfile
update prebuild and manual-build version, now both two are all the same:
godwoken: v0.2.3
godwoken-web3: v0.2.1
=> Update both modes version: gw to v0.2.3

docker/gen-godwoken-schema/entrypoint.sh
=> fix: gen-godwoken-schema  entrypoint.sh

godwoken_entrypoint.sh, gw_util.sh
Set l1_sudt_script_type_hash in rollup-config.json before deploy genesis
=> fix: zero l1_sudt_script_type_hash in genesis rollup global state

Makefile, godwoken_entrypoint.sh, gw_util.sh
side-effects: use real polyjuice-validator now.
=> Refactor prepare scripts and godwoken deployment process

godwoken_entrypoint.sh
https://github.com/nervosnetwork/godwoken/blob/d64926aa667a59e92cb2c71482989cfc0df4d0c8/crates/block-producer/src/utils.rs#L293-L298
=> Set GODWOKEN_DEBUG=true to enable cycles logs

gw_util.sh
fix: sed: can't read /code/workspace/config.toml}
=> Fix typo in set_key_value_in_toml()

Makefile
use target dependency instead of calling another target explicitly,  avoid running another instance of make.
=> use dependencies in Makefile

docker/.build.mode.env, gw_util.sh
https://unix.stackexchange.com/a/644169 Dash, Yash and Zsh works, but Bash not.
=> fix: EXIT_IF_START_FAIL in bash shell 

Makefile
https://github.com/RetricSu/godwoken-kicker/issues/169
=> fix: manual polyman db cache after make clean-cache

docker/docker-compose.yml
https://github.com/RetricSu/godwoken-kicker/pull/162
=> fix(develop): redis save rdb to cache mount dir with root

.github/workflows/start-test.yml, Makefile, docker/.build.mode.env, gw_util.sh
in godwoken-test
https://github.com/nervosnetwork/godwoken-tests/blob/v1/.github/workflows/reusable-integration-test-v1.yml
=> Godwoken v1: Run integration-test by calling reusable-workflow

.gitignore, docker/.build.mode.env
- related PR
https://github.com/nervosnetwork/godwoken-web3/pull/199
=> Update the web3 images

docker/docker-compose.yml
- https://github.com/RetricSu/godwoken-kicker/issues/198
=> enhence: add service restart policy

docker/manual-image/Dockerfile, kicker
=> fix(kicker): manual build godwoken failed in ci

docker/.build.mode.env, docker/docker-compose.yml
```js
"labels": {
"ref.component.godwoken-polyjuice": "refs/pull/134/head b14b405",
"ref.component.godwoken": "fix-producer.account_id 0805553f",
"ref.component.ckb-production-scripts": "rc_lock 47358ce",
"ref.component.godwoken-scripts": "compatibility-breaking-changes 81676d9",
}
```
=> Update the package refs

docs/manual-build.md, kicker
- https://github.com/RetricSu/godwoken-kicker/issues/197
=> Enhence manual build mode

docker/docker-compose.yml
This PR updates Godwoken image to [v1-godwoken-pull-652-202204130926](https://github.com/keroro520/godwoken-docker-prebuilds/pkgs/container/godwoken-prebuilds/18956353?tag=v1-godwoken-pull-652-202204130926), which includes a [Godwoken bugfix](https://github.com/nervosnetwork/godwoken/pull/652) that may cause [Kicker fails to start](https://github.com/RetricSu/godwoken-kicker/issues/215).
Image labels:
```
"labels": {
"ref.component.godwoken-polyjuice-sha1": "941aa6eb1052c4112ba32d47136607323a1f022a",
"org.opencontainers.image.title": "godwoken-docker-prebuilds",
"ref.component.godwoken-scripts-sha1": "81676d9d53ffdf5bbaa60483928d07da16eb4a88",
"org.opencontainers.image.revision": "6df9fb11c5704fc9ed8772fcdc121058cf5159f5",
"ref.component.godwoken-polyjuice": "v1.0.0-rc1 941aa6e", …
```
=> chore: update godwoken image, pr 652

.github/workflows/hardhat-simple-project.yml
fix Error HH12: Trying to use a non-local installation of Hardhat, which is not supported.
For more info go to https://hardhat.org/HH12
=> Fix simple test CI

docker/.build.mode.env, docker/docker-compose.yml, docker/layer2/config/rollup-config.json, docker/layer2/config/scripts-config.json, docker/layer2/entrypoint.sh
- https://github.com/nervosnetwork/godwoken/blob/e7be07535e24e83d2dc546bd659d1dc90e7a2850/docs/CHANGES.md
- https://github.com/nervosnetwork/godwoken/pull/649
- https://github.com/nervosnetwork/godwoken-web3/pull/282
=> Adapt Godwoken v1.1

.github/workflows/hardhat-simple-project.yml, docs/hardhat-simple-project.md
* Related issue: https://github.com/RetricSu/godwoken-kicker/pull/224
=> fix(docs): avoid HH12 issue

.gitignore, docker/docker-compose.yml, docker/layer2-v0/config/poa-config.json, docker/layer2-v0/config/rollup-config.json, docker/layer2-v0/config/scripts-config.json, docker/layer2-v0/entrypoint.sh, docker/manual-godwoken-v0.compose.yml, kicker
- new `START_GODWOKEN_V0` environment variable, set true to start godwoken v0.10
- fix kicker `get-balance`
- new kicker `deposit-v0`
- new kicker `withdraw-v0-to-v1`
=> feat: add godwoken v0 support

.gitignore, docker/docker-compose.yml, docker/layer2-v0/config/poa-config.json, docker/layer2-v0/config/rollup-config.json, docker/layer2-v0/config/scripts-config.json, docker/layer2-v0/entrypoint.sh, docker/layer2-v0/healthcheck.sh, docker/manual-godwoken-v0.compose.yml, kicker
- Add the test case about fast-withdrawal from v0 to v1
- change Layer2 CKB decimal to 18
```js
godwoken
- https://github.com/nervosnetwork/godwoken/pull/675
godwoken-scripts
- https://github.com/nervosnetwork/godwoken-scripts/pull/118
godowken-polyjuice
- https://github.com/nervosnetwork/godwoken-polyjuice/pull/146
godowken-tests
- https://github.com/nervosnetwork/godwoken-tests/pull/105
```
=> v1.1: Update godwoken-prebuilds image

docker/docker-compose.yml
https://github.com/nervosnetwork/godwoken/blob/692fbef848ee730ccf9f101db3422aa46276dd29/CHANGELOG.md#v110-beta---2022-05-08
=> Update prebuilt images of Godwoken v1.1.0-beta

docker/docker-compose.yml
- nervos/godwoken-web3-indexer-prebuilds:v1.1.0-beta
- nervos/godwoken-web3-prebuilds:v1.1.0-beta
- ghcr.io/nervosnetwork/godwoken-prebuilds:v1.1.0-beta.1
=> Update the images of v1.1.0-beta

docker/docker-compose.yml
ghcr.io/keroro520/godwoken-prebuilds:v1-godwoken-d3eb41a-202205310512 brings a godwoken bugfix:
- https://github.com/nervosnetwork/godwoken/pull/709
=> chore: update godwoken image v1-godwoken-d3eb41a

docker/docker-compose.yml
* Contract should be null when not exists by @Flouse @classicalliu  in https://github.com/nervosnetwork/godwoken-web3/pull/371
* Cherry pick publish support workflow dispatch by @keroro520 in https://github.com/nervosnetwork/godwoken-web3/pull/373
* chore: bump v1.1.1-rc1 by @RetricSu in https://github.com/nervosnetwork/godwoken-web3/pull/370
**Full Changelog**: https://github.com/nervosnetwork/godwoken-web3/compare/v1.1.0-rc1...v1.1.1-rc1
=> chore: bump web3/indexer v1.1.1-rc1

README.md, docs/CONTRIBUTING.md
- https://github.com/RetricSu/godwoken-kicker/issues/264
=> docs: add CONTRIBUTING.md

README.md, docs/kicker-start.md
https://github.com/RetricSu/godwoken-kicker/issues/264#issuecomment-1146943729
=> docs: switch default branch to "master"

.github/workflows/hardhat-simple-project.yml
https://github.com/RetricSu/godwoken-kicker/runs/7173630118?check_suite_focus=true#step:23:16
=> chore: tune deposit balance to 10000

kicker
deps:
- https://github.com/nervosnetwork/godwoken/pull/744
=> feat: support sudt-transfer

docker/layer2/entrypoint-readonly.sh
related pr
- https://github.com/nervosnetwork/godwoken/pull/768
=> feat(entrypoint-readonly): remove block producer wallet config

docker/docker-compose.yml
https://github.com/nervosnetwork/godwoken/releases/tag/v1.7.0-rc1
=> Bump godwoken-prebuilds to 1.7-rc

docker/docker-compose.yml
https://github.com/godwokenrises/godwoken-docker-prebuilds/pkgs/container/godwoken-prebuilds/49615211?tag=dev-poly1.5.0
"ref.component.godwoken-polyjuice": "1.5.0  0cc7a81",
"ref.component.godwoken": "develop  6ae8317",
=> Bump godwoken-prebuilds to dev-poly1.5.0

docs/kicker-start.md
master branch has been deleted, use the develop branch
=> docs: update kicker-start.md

docker/docker-compose.yml
This version enables SMT trie feature.
- https://github.com/godwokenrises/godwoken/pull/859
=> Bump to Godwoken v1.8.0-rc3-smt-trie

docker/layer2-v0/entrypoint.sh
This reverts commit 04edad1b8ba009892c1dfb47f41a89f6da8c99e7.
=> Revert "Adapt for v1 config file change (#341)"

kicker
Run `./kicker start` when zero address account not exists
```console
:> docker-compose -f docker/docker-compose.yml up -d --build
Creating network "docker_default" with the default driver
Creating docker_ckb_1       ... done
Creating docker_redis_1                          ... done
Creating docker_ckb-miner_1 ... done
Creating docker_postgres_1                       ... done
Creating docker_check-ckb-started-successfully_1 ... done
Creating docker_ckb-indexer_1                    ... done
Creating docker_godwoken_1                       ... done
Creating docker_godwoken-readonly_1              ... done
Creating docker_web3_1                           ... done
Creating docker_web3-indexer_1                   ... done
[start] Services started successfully
% Total    % Received % Xferd …
```
=> feat: Auto deposit zero address when start
