godwokenrises/godwoken-kicker

- godwoken_entrypoint.sh
It used to default to 127.0.0.1:8116 in ckb-indexer therefore it wasn't accessible outside of the Docker container. Changing 127.0.0.1 to 0.0.0.0 host does the job.
The hostname is verified in JSON RPC HTTP crate in Rust in ckb-indexer.
> fix: expose ckb-indexer outside of Docker container on 8116 port

- ckb-data/ckb.toml
- docker/docker-compose.yml
Subscriptions require a full duplex connection. CKB offers such connections in the form of TCP (enable with rpc.tcp_listen_address configuration option) and WebSockets (enable with rpc.ws_listen_address).
> enable CKB RPC ws_listen_address in ckb.toml

- docker/layer2/entrypoint.sh
1. remove `GODWOKEN_DEBUG` since it is deprecated in the godwoken.
2. set default log level to info so we can get more useful logs.
> chore: set default log level to info

- README.md
The module has been renamed from capsule to ckb-capsule on cargo.
> docs: rename capsule to ckb-capsule

- .github/workflows/godwoken-tests.yml
- .github/workflows/schedule.yml
- .github/workflows/start-test.yml
There are three workflows:
* [start-test.yml](https://github.com/RetricSu/godwoken-kicker/blob/d6cf26973b501c0eb52ab551993a22f26f0c16ca/.github/workflows/start-test.yml) does a simple start - stop circle.
* [godwoken-tests.yml](https://github.com/RetricSu/godwoken-kicker/blob/d6cf26973b501c0eb52ab551993a22f26f0c16ca/.github/workflows/godwoken-tests.yml) executes contract tests provided by godwoken-test.
* [schedule.yml](https://github.com/RetricSu/godwoken-kicker/blob/d6cf26973b501c0eb52ab551993a22f26f0c16ca/.github/workflows/schedule.yml) schedule running godwoken-tests in manual-build mode every 6 hours.
> feat: schedule running tests

- .github/workflows/hardhat-simple-project.yml
- README.md
- docker/layer2/setup-godwoken.sh
- docs/hardhat-simple-project.md
- docs/kicker-start.md
- kicker
Usage:
```
$ ./kicker deposit 0x618cc3C660cEBFDbA8570CA739b1744AE3E2553a 1000
$ ./kicker get-balance 0x618cc3C660cEBFDbA8570CA739b1744AE3E2553a
```
`kicker deposit` deposits capacity from account `config/private_key` to the given eth-address.
> feat: support deposit/get-balance instructions

- kicker
The result of `wc -l` command execution has spaces and "0" are not equal
> fix clean cmd failed in mac(m1)

- docker/layer2/entrypoint.sh
```
$ bash -c 'echo $((1984 << 32 + 4))'
136339441844224
$ zsh -c 'echo $((1984 << 32 + 4))'
8521215115268
```
```
$bash -c 'echo $(((1984 << 32 ) + 4))'
8521215115268
$ zsh -c 'echo $(((1984 << 32 ) + 4))'
8521215115268
```
> fix: incorrectly use bit shift priority

- docker/layer1/ckb/ckb.toml
CKB seems unstable: https://github.com/RetricSu/godwoken-kicker/runs/6071639933?check_suite_focus=true
I would like to enable CKB's debug logs to find out why.
> chore: enable ckb debug logs

- docker/docker-compose.yml
- change Layer2 CKB decimals to 18
```js
godwoken
- https://github.com/nervosnetwork/godwoken/pull/675
godwoken-scripts
- https://github.com/nervosnetwork/godwoken-scripts/pull/118
godowken-polyjuice
- https://github.com/nervosnetwork/godwoken-polyjuice/pull/146
godowken-tests
- https://github.com/nervosnetwork/godwoken-tests/pull/105
```
> v1.1: change Layer2 CKB decimals to 18

- docker/docker-compose.yml
Why: Web3-indexer will request web3 service throught HTTP interfaces. So
it has to wait until web3 service started and become healthy.
How: web3-indexer::depends_on::condition::web3::service_healthy
> fix: web3-indexer depends_on web3 healthy

- .gitignore
- docker/docker-compose.yml
- docker/layer2/config/web3-config.env
- docker/layer2/entrypoint.sh
- kicker
- Thanks https://github.com/nervosnetwork/godwoken-web3/issues/200
> refactor: Simplify Web3 configuration

- docker/layer2/entrypoint.sh
So that the deposit does not conflict with godwoken block submission etc.
> chore: deposit from ckb-miner-and-faucet in godwoken entrypoint after godwoken is started

- docker/docker-compose.yml
Why: This new image contains several godwoken's bugfixes/enhancements related to kicker:
- https://github.com/nervosnetwork/godwoken/pull/705
- https://github.com/nervosnetwork/godwoken/pull/704
- https://github.com/nervosnetwork/godwoken/pull/702
"ref.component.godwoken": [f86d655](https://github.com/nervosnetwork/godwoken/commit/f86d6559951cef1be6cd64cf8091d9820f3e110f)
> chore: update godwoken image v1-godwoken-f86d655

- .github/workflows/godwoken-tests.yml
After using the simplified godwoken test workflow, we can remove the `.build.mode.env` now
> feat: reuse simplified godwoken-test workflow

- docker/docker-compose.yml
* fix(1.1): topic param can be null by @RetricSu in https://github.com/nervosnetwork/godwoken-web3/pull/375
* chore(deps): bump protobufjs from 6.11.2 to 6.11.3 by @RetricSu in https://github.com/nervosnetwork/godwoken-web3/pull/383
* chore: bump v1.1.2-rc1 by @RetricSu in https://github.com/nervosnetwork/godwoken-web3/pull/384
**Full Changelog**: https://github.com/nervosnetwork/godwoken-web3/compare/v1.1.1-rc1...v1.1.2-rc1
> chore: bump web3/indexer v1.1.2-rc1

- docker/docker-compose.yml
- docker/layer2/entrypoint.sh
- docker/web3/entrypoint.sh
Healthcheck params: a smaller `retries` makes `docker ps` `healthy` information more accurate, while a smaller `interval` makes `kicker start` faster.
Not restarting godwoken in `entrypoint.sh` also makes `docker ps` `healthy` information more accurate.
Using `init: true` makes `kicker stop` much faster and handles reaped processes.
> Make docker ps more accurate and start/stop faster

- docker/manual-polyjuice.compose.yml
- docker/manual-scripts.compose.yml
`godwoken` and `godwoken-readonly` should share the same Polyjuice scripts and Godwoken scripts.
> fix: godwoken-readonly should update as well when manual build polyjuice

- docker/manual-image/Dockerfile
Fixes https://github.com/RetricSu/godwoken-kicker/issues/312#issuecomment-1245104760
ckb-capsule cannot be compiled when building [manual-image/Dockerfile] due to a lack of git installed, required for the compiling process: https://github.com/nervosnetwork/capsule/blob/3e304767d8d4e2b6a445dce0266cb810d1961cb4/build.rs#L13-L22
```rust
// get commit id
let commit_id = std::process::Command::new("git")
.args(&[
"describe",
"--dirty",
"--always",
"--match",
"__EXCLUDE__",
"--abbrev=7",
])
.output()
.ok()
.and_then(|r| String::from_utf8(r.stdout).ok())
.expect("commit id");
```
> fix: install git before installing capsule

- kicker
The omni-lock script is stable enough to use the prebuilt binary is enough
> chore: use prebuild omni-lock script

- kicker
The `web3-indexer` needs to reference godwoken crates by path, so we should mount the monorepo into the docker volume.
> fix: mount monorepo into docker when build web3-indexer

- docker/layer2-v0/entrypoint.sh
V1 config file generated by toml-edit uses double quote.
> Adapt for v1 config file change

- docs/manual-build.md
- kicker
The builtin consensus config and binaries are not required on a  Godwoken devnet, so `--features gw-config/no-builtin` is appended to `cargo build` arguments.
> manual_build: build Godwoken with `gw-config/no-builtin` feature

- kicker
to avoid `out of disk` issue in CI
- [godwoken-tests / test-on-devnet-v1](https://github.com/godwokenrises/godwoken/actions/runs/6515541217/job/17698087986#step:1:56)
You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 78 MB
> https://github.com/godwokenrises/godwoken/actions/runs/6515541217?pr=1097
- [web3-unit-tests](https://github.com/godwokenrises/godwoken/actions/runs/6515541179/job/17698087879#step:1:28)
You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 51 MB
> https://github.com/godwokenrises/godwoken/actions/runs/6515541179?pr=1097
> fix(kicker init): remove target/release/examples 

- .github/workflows/godwoken-tests.yml
- docker/docker-compose.yml
- kicker
Diskspace is limited in GitHub Actions, so we need to manually clean the middle artifacts
> CI: add MANUAL_BUILD tests
